{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chloemlla.lumen",
    "module": "lumen-crash-core",
    "version": "0.1.0-2207c976",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lumen-crash-core-0.1.0-2207c976.aar",
          "url": "lumen-crash-core-0.1.0-2207c976.aar",
          "size": 91400,
          "sha512": "56efb6f3dda08a29eacd4f6c17125572887fd3cd233c432f2a8957971504be4175b10cb6893f4cebb0db2e877c39dbfef19c5ed30b1b615272270e55344c8291",
          "sha256": "ccfe3b61f8c7796ba334002da2689c9ad21453b14d7e74e9edcab037da9a4367",
          "sha1": "133bc6ea81e0f6e44923e972fe13d77bd13885ee",
          "md5": "e877b4b9086d6701ef3318b78584fa48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "lumen-crash-core-0.1.0-2207c976.aar",
          "url": "lumen-crash-core-0.1.0-2207c976.aar",
          "size": 91400,
          "sha512": "56efb6f3dda08a29eacd4f6c17125572887fd3cd233c432f2a8957971504be4175b10cb6893f4cebb0db2e877c39dbfef19c5ed30b1b615272270e55344c8291",
          "sha256": "ccfe3b61f8c7796ba334002da2689c9ad21453b14d7e74e9edcab037da9a4367",
          "sha1": "133bc6ea81e0f6e44923e972fe13d77bd13885ee",
          "md5": "e877b4b9086d6701ef3318b78584fa48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lumen-crash-core-0.1.0-2207c976-sources.jar",
          "url": "lumen-crash-core-0.1.0-2207c976-sources.jar",
          "size": 25887,
          "sha512": "2f08604c36025fa8fc31dc4683924f7e4af727e73d4fdf9644880d251fd219eb6c2515ad70517c57214747c9046643b5eb764b09da223122d15d82223735c953",
          "sha256": "a14f2d8f011e11b20547677dfb7873d98ce55f8c864a93e211ea915272d8d037",
          "sha1": "3863a73147c29f1dc76faf5f8debfbcf576042f0",
          "md5": "bab6e2e8ba547e2d251abe68dd30c495"
        }
      ]
    }
  ]
}
